# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lumeos-aurora
description: LumeOS Aurora

# O novo repositório unificado deles
base-image: ghcr.io/ublue-os/bazzite
# A tag agora carrega a interface (kde) e a versão estável do Fedora (41)
image-version: kde-41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - google-chrome-stable
      - google-earth-pro-stable
      - spotify-client
      - kdenlive
      - onlyoffice-desktopeditors
      - vlc
      - papirus-icon-theme
    remove:
      - kfind
      - libreoffice-core

  - type: script
    scripts:
      - customizar_lumeos.sh
