# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lumeos-aurora
description: LumeOS Aurora

base-image: ghcr.io/ublue-os/bazzite-kde
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Gerenciador do Bazzite para pacotes e remoção do kfind
  - type: rpm-ostree
    install:
      - google-chrome-stable
      - google-earth-pro-stable
      - spotify-client
      - kdenlive
      - onlyoffice-desktopeditors
      - vlc
      - papirus-icon-theme
    remove:
      - kfind

  # Nosso script de customização
  - type: script
    scripts:
      - customizar_lumeos.sh
