# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lumeos-aurora
description: LumeOS Aurora

base-image: ghcr.io/ublue-os/bazzite-kde
image-version: latest

branding:
  website: "https://lumeos.org"

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Gerenciador correto do Bazzite para instalar os apps e tirar a carniça do kfind
  - type: rpm-ostree
    install:
      - google-chrome-stable
      - google-earth-pro-stable
      - spotify-client
      - kdenlive
      - onlyoffice-desktopeditors
      - vlc
      - papirus-icon-theme
    remove:
      - kfind

  # Aqui chamamos o nosso script de customização de logos e nomes
  - type: script
    scripts:
      - customizar_lumeos.sh

  # Mantém esse cara! Ele é vital para gerar as chaves de segurança da ISO
  - type: signing
