name: Build LumeOS ISO

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar pasta de saída
        run: mkdir -p ${{ github.workspace }}/output

      - name: Rodar Bootc Image Builder
        run: |
          sudo podman run --rm --privileged \
            -v ${{ github.workspace }}/output:/output \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type iso \
            ghcr.io/lakomby/lumeos-aurora:26

      - name: Upload da ISO como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: LumeOS-Aurora-ISO
          path: ${{ github.workspace }}/output/bootiso/install.iso
