name: Build LumeOS ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar pasta de saída
        run: mkdir -p ${{ github.workspace }}/output

      - name: Login no GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Puxar a imagem do LumeOS
        run: sudo podman pull ghcr.io/lakomby/lumeos-aurora:latest

      - name: Tag local para evitar erro de distro
        run: sudo podman tag ghcr.io/lakomby/lumeos-aurora:latest localhost/lumeos-aurora:latest

      - name: Rodar Bootc Image Builder (Força Bruta Local)
        run: |
          sudo podman run --rm --privileged \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            -v ${{ github.workspace }}/output:/output \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type iso \
            --rootfs xfs \
            --target-no-signature-verification \
            localhost/lumeos-aurora:latest

      - name: Upload da ISO para Download
        uses: actions/upload-artifact@v4
        with:
          name: LumeOS-Aurora-ISO
          path: ${{ github.workspace }}/output/bootiso/install.iso
